# Generated by Django 2.2.1 on 2020-02-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱账户')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
            ],
            options={
                'db_table': 'loguser',
                'verbose_name_plural': '用户信息表',
            },
        ),
    ]
