# Generated by Django 2.2.1 on 2020-02-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0003_goods_goods_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='state',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
    ]
