# Generated by Django 2.2.1 on 2020-03-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0009_auto_20200304_2108'),
        ('Buyer', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('postcode', models.CharField(max_length=10, verbose_name='邮编')),
                ('name', models.CharField(max_length=10, verbose_name='收件人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.LoginUser')),
            ],
            options={
                'verbose_name_plural': '收货地址',
                'db_table': 'shaddress',
            },
        ),
    ]
