# Generated by Django 2.2.1 on 2020-03-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_shaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shaddress',
            name='state',
            field=models.IntegerField(default=0, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
