# Generated by Django 2.2.1 on 2020-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20200217_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='/images/01.jpg', upload_to='images', verbose_name='图片'),
            preserve_default=False,
        ),
    ]
