# Generated by Django 2.2.1 on 2020-02-18 02:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_article_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=ckeditor.fields.RichTextField(verbose_name='时间日期'),
        ),
    ]
