# Generated by Django 2.2.1 on 2020-02-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20200218_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click_l',
            field=models.IntegerField(default=0, verbose_name='点击率'),
        ),
        migrations.AddField(
            model_name='article',
            name='recom',
            field=models.IntegerField(default=0, verbose_name='推荐'),
        ),
    ]
