# Generated by Django 2.2.1 on 2020-02-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(verbose_name='时间日期'),
        ),
    ]
