# Generated by Django 2.2.1 on 2020-02-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Yonghu',
        ),
    ]
