# Generated by Django 2.2.1 on 2020-02-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_auto_20200218_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='yonghu',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
