# Generated by Django 2.2.1 on 2020-02-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_loginuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
            preserve_default=False,
        ),
    ]
