# Generated by Django 2.2.1 on 2020-02-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_loginuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
    ]
