# Generated by Django 2.2.1 on 2020-02-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_auto_20200226_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodstype',
            options={'verbose_name_plural': '类型表'},
        ),
    ]
