# Generated by Django 2.2.1 on 2020-03-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0007_auto_20200227_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32, verbose_name='用户名邮箱')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'validcode',
                'verbose_name_plural': '验证码表',
            },
        ),
    ]
